import { Button, Input, Form, Toast, TextArea, Cascader } from 'antd-mobile'
import React, { useEffect, useState } from 'react'

interface choiceCountryProps {
  value: string
  onChange: (value: string) => void
}

const choiceCountry = ({ value, onChange }: choiceCountryProps) => {
  const [visible, setVisible] = useState(false)
  return (
    <div className="main w-[100%] flex-1">
      <div className="w-[100%] " onClick={() => setVisible(true)}>
        {value ? (
          <div className="val">{value}</div>
        ) : (
          <div className="text-[#ccc] h-[25.5px] text-[17px]">地区</div>
        )}
      </div>
      <Cascader
        options={countryData}
        visible={visible}
        onClose={() => {
          setVisible(false)
        }}
        onConfirm={(v) => onChange(v.join('-'))}
      />
    </div>
  )
}

let countryData = [
  { value: '北京' },
  { value: '上海' },
  {
    value: '四川',
    children: [
      { value: '成都' },
      { value: '自贡' },
      { value: '攀枝花' },
      { value: '泸州' },
      { value: '德阳' },
      { value: '绵阳' },
      { value: '广元' },
      { value: '遂宁' },
      { value: '内江' },
      { value: '乐山' },
      { value: '南充' },
      { value: '眉山' },
      { value: '宜宾' },
      { value: '广安' },
      { value: '达州' },
      { value: '雅安' },
      { value: '巴中' },
      { value: '资阳' },
      { value: '阿坝' },
      { value: '甘孜' },
      { value: '凉山' },
    ],
  },
  {
    value: '广东',
    children: [
      { value: '广州' },
      { value: '深圳' },
      { value: '珠海' },
      { value: '汕头' },
      { value: '韶关' },
      { value: '佛山' },
      { value: '江门' },
      { value: '湛江' },
      { value: '茂名' },
      { value: '肇庆' },
      { value: '惠州' },
      { value: '梅州' },
      { value: '汕尾' },
      { value: '河源' },
      { value: '阳江' },
      { value: '清远' },
      { value: '东莞' },
      { value: '中山' },
      { value: '潮州' },
      { value: '揭阳' },
      { value: '云浮' },
    ],
  },
  {
    value: '浙江',
    children: [
      { value: '杭州' },
      { value: '宁波' },
      { value: '温州' },
      { value: '绍兴' },
      { value: '湖州' },
      { value: '嘉兴' },
      { value: '金华' },
      { value: '衢州' },
      { value: '舟山' },
      { value: '台州' },
      { value: '丽水' },
    ],
  },
  {
    value: '安徽',
    children: [
      { value: '合肥' },
      { value: '芜湖' },
      { value: '蚌埠' },
      { value: '淮南' },
      { value: '马鞍山' },
      { value: '淮北' },
      { value: '铜陵' },
      { value: '安庆' },
      { value: '黄山' },
      { value: '滁州' },
      { value: '阜阳' },
      { value: '宿州' },
      { value: '六安' },
      { value: '亳州' },
      { value: '池州' },
      { value: '宣城' },
    ],
  },
  {
    value: '江苏',
    children: [
      { value: '南京' },
      { value: '无锡' },
      { value: '徐州' },
      { value: '常州' },
      { value: '苏州' },
      { value: '南通' },
      { value: '连云港' },
      { value: '淮安' },
      { value: '盐城' },
      { value: '扬州' },
      { value: '镇江' },
      { value: '泰州' },
      { value: '宿迁' },
    ],
  },
  { value: '天津' },
  { value: '重庆' },

  {
    value: '山东',
    children: [
      { value: '济南' },
      { value: '青岛' },
      { value: '淄博' },
      { value: '枣庄' },
      { value: '东营' },
      { value: '烟台' },
      { value: '潍坊' },
      { value: '济宁' },
      { value: '泰安' },
      { value: '威海' },
      { value: '日照' },
      { value: '临沂' },
      { value: '德州' },
      { value: '聊城' },
      { value: '滨州' },
      { value: '菏泽' },
    ],
  },

  {
    value: '河北',
    children: [
      { value: '石家庄' },
      { value: '唐山' },
      { value: '秦皇岛' },
      { value: '邯郸' },
      { value: '邢台' },
      { value: '保定' },
      { value: '张家口' },
      { value: '承德' },
      { value: '沧州' },
      { value: '廊坊' },
      { value: '衡水' },
    ],
  },
  {
    value: '河南',
    children: [
      { value: '郑州' },
      { value: '开封' },
      { value: '洛阳' },
      { value: '平顶山' },
      { value: '安阳' },
      { value: '鹤壁' },
      { value: '新乡' },
      { value: '焦作' },
      { value: '濮阳' },
      { value: '许昌' },
      { value: '漯河' },
      { value: '三门峡' },
      { value: '南阳' },
      { value: '商丘' },
      { value: '信阳' },
      { value: '周口' },
      { value: '驻马店' },
      { value: '济源' },
    ],
  },
  {
    value: '湖北',
    children: [
      { value: '武汉' },
      { value: '黄石' },
      { value: '十堰' },
      { value: '宜昌' },
      { value: '襄阳' },
      { value: '鄂州' },
      { value: '荆门' },
      { value: '孝感' },
      { value: '荆州' },
      { value: '黄冈' },
      { value: '咸宁' },
      { value: '随州' },
      { value: '恩施' },
      { value: '仙桃' },
      { value: '潜江' },
      { value: '天门' },
      { value: '神农架' },
    ],
  },
  {
    value: '湖南',
    children: [
      { value: '长沙' },
      { value: '株洲' },
      { value: '湘潭' },
      { value: '衡阳' },
      { value: '邵阳' },
      { value: '岳阳' },
      { value: '常德' },
      { value: '张家界' },
      { value: '益阳' },
      { value: '郴州' },
      { value: '永州' },
      { value: '怀化' },
      { value: '娄底' },
      { value: '湘西' },
    ],
  },
  {
    value: '福建',
    children: [
      { value: '福州' },
      { value: '厦门' },
      { value: '莆田' },
      { value: '三明' },
      { value: '泉州' },
      { value: '漳州' },
      { value: '南平' },
      { value: '龙岩' },
      { value: '宁德' },
    ],
  },
  {
    value: '辽宁',
    children: [
      { value: '沈阳' },
      { value: '大连' },
      { value: '鞍山' },
      { value: '抚顺' },
      { value: '本溪' },
      { value: '丹东' },
      { value: '锦州' },
      { value: '营口' },
      { value: '阜新' },
      { value: '辽阳' },
      { value: '盘锦' },
      { value: '铁岭' },
      { value: '朝阳' },
      { value: '葫芦岛' },
    ],
  },
  {
    value: '吉林',
    children: [
      { value: '长春' },
      { value: '吉林市' },
      { value: '四平' },
      { value: '辽源' },
      { value: '通化' },
      { value: '白山' },
      { value: '松原' },
      { value: '白城' },
      { value: '延边' },
    ],
  },
  {
    value: '黑龙江',
    children: [
      { value: '哈尔滨' },
      { value: '齐齐哈尔' },
      { value: '鸡西' },
      { value: '鹤岗' },
      { value: '双鸭山' },
      { value: '大庆' },
      { value: '伊春' },
      { value: '佳木斯' },
      { value: '七台河' },
      { value: '牡丹江' },
      { value: '黑河' },
      { value: '绥化' },
      { value: '大兴安岭' },
    ],
  },
  {
    value: '陕西',
    children: [
      { value: '西安' },
      { value: '铜川' },
      { value: '宝鸡' },
      { value: '咸阳' },
      { value: '渭南' },
      { value: '延安' },
      { value: '汉中' },
      { value: '榆林' },
      { value: '安康' },
      { value: '商洛' },
    ],
  },
  {
    value: '甘肃',
    children: [
      { value: '兰州' },
      { value: '嘉峪关' },
      { value: '金昌' },
      { value: '白银' },
      { value: '天水' },
      { value: '武威' },
      { value: '张掖' },
      { value: '平凉' },
      { value: '酒泉' },
      { value: '庆阳' },
      { value: '定西' },
      { value: '陇南' },
      { value: '临夏' },
      { value: '甘南' },
    ],
  },
  { value: '青海' },
  {
    value: '广西',
    children: [
      { value: '南宁' },
      { value: '柳州' },
      { value: '桂林' },
      { value: '梧州' },
      { value: '北海' },
      { value: '防城港' },
      { value: '钦州' },
      { value: '贵港' },
      { value: '玉林' },
      { value: '百色' },
      { value: '贺州' },
      { value: '河池' },
      { value: '来宾' },
      { value: '崇左' },
    ],
  },
  {
    value: '海南',
    children: [
      { value: '海口' },
      { value: '三亚' },
      { value: '三沙' },
      { value: '儋州' },
    ],
  },
  {
    value: '贵州',
    children: [
      { value: '贵阳' },
      { value: '六盘水' },
      { value: '遵义' },
      { value: '安顺' },
      { value: '毕节' },
      { value: '铜仁' },
      { value: '黔西南' },
      { value: '黔东南' },
      { value: '黔南' },
    ],
  },
  {
    value: '云南',
    children: [
      { value: '昆明' },
      { value: '曲靖' },
      { value: '玉溪' },
      { value: '保山' },
      { value: '昭通' },
      { value: '丽江' },
      { value: '普洱' },
      { value: '临沧' },
      { value: '楚雄' },
      { value: '红河' },
      { value: '文山' },
      { value: '西双版纳' },
      { value: '大理' },
      { value: '德宏' },
      { value: '怒江' },
      { value: '迪庆' },
    ],
  },
  {
    value: '西藏',
    children: [
      { value: '拉萨' },
      { value: '日喀则' },
      { value: '昌都' },
      { value: '山南' },
      { value: '那曲' },
      { value: '阿里' },
      { value: '林芝' },
    ],
  },
  {
    value: '新疆',
    children: [
      { value: '乌鲁木齐' },
      { value: '克拉玛依' },
      { value: '吐鲁番' },
      { value: '哈密' },
      { value: '昌吉' },
      { value: '博尔塔拉' },
      { value: '巴音郭楞' },
      { value: '阿克苏' },
      { value: '克孜勒苏' },
      { value: '喀什' },
      { value: '和田' },
      { value: '伊犁' },
      { value: '塔城' },
      { value: '阿勒泰' },
    ],
  },
  {
    value: '内蒙古',
    children: [
      { value: '呼和浩特' },
      { value: '包头' },
      { value: '乌海' },
      { value: '赤峰' },
      { value: '通辽' },
      { value: '鄂尔多斯' },
      { value: '呼伦贝尔' },
      { value: '巴彦淖尔' },
      { value: '乌兰察布' },
      { value: '兴安' },
      { value: '锡林郭勒' },
      { value: '阿拉善' },
    ],
  },
  {
    value: '宁夏',
    children: [
      { value: '银川' },
      { value: '石嘴山' },
      { value: '吴忠' },
      { value: '固原' },
      { value: '中卫' },
    ],
  },
  {
    value: '江西',
    children: [
      { value: '南昌' },
      { value: '景德镇' },
      { value: '萍乡' },
      { value: '九江' },
      { value: '新余' },
      { value: '鹰潭' },
      { value: '赣州' },
      { value: '吉安' },
      { value: '宜春' },
      { value: '抚州' },
      { value: '上饶' },
    ],
  },
  {
    value: '山西',
    children: [
      { value: '太原' },
      { value: '大同' },
      { value: '阳泉' },
      { value: '长治' },
      { value: '晋城' },
      { value: '朔州' },
      { value: '晋中' },
      { value: '运城' },
      { value: '忻州' },
      { value: '临汾' },
      { value: '吕梁' },
    ],
  },
  { value: '香港' },
  { value: '澳门' },
  {
    value: '台湾',
    children: [
      { value: '台北' },
      { value: '高雄' },
      { value: '台中' },
      { value: '台南' },
      { value: '新北' },
      { value: '桃园' },
      { value: '基隆' },
      { value: '新竹' },
      { value: '嘉义' },
    ],
  },
]
countryData = countryData.map((e: any) => {
  e.label = e.value
  if (e.children) {
    e.children = e.children.map((child: any) => {
      child.label = child.value
      return child
    })
  }
  return e
})

export default choiceCountry
